from typing import Dict, Any
import json

class IntelligenceExporter:
    """Formats intelligence data into Markdown or JSON briefs."""

    def export_markdown(self, dossier: Dict[str, Any], narrative: str) -> str:
        return f"""# Executive Intelligence Brief: {dossier.get('domain', 'Target')}

## Executive Summary
{narrative}

## Telemetry
- Latency: {dossier.get('telemetry', {}).get('latency_ms')}ms
- Status: {dossier.get('telemetry', {}).get('status')}

## Structural Fingerprint
Detected assets indicate reliance on modern UI frameworks and edge delivery networks.

*Generated by Nexra Intelligence Analytics*
"""

    def export_json(self, dossier: Dict[str, Any]) -> str:
        return json.dumps(dossier, indent=2)

intelligence_exporter = IntelligenceExporter()
